{"cells":[{"cell_type":"code","source":"! pip install dash\n! pip install dash-core-components\n! pip install dash-html-components\n! pip install dash-renderer\n! pip install statsmodels","metadata":{"tags":[],"cell_id":"774689ca9cf84b46a42f71e74d16e168","source_hash":"a541046c","execution_start":1683104980886,"execution_millis":19565,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Collecting dash\n  Downloading dash-2.9.3-py3-none-any.whl (10.2 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.2/10.2 MB\u001b[0m \u001b[31m95.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting dash-core-components==2.0.0\n  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)\nCollecting dash-table==5.0.0\n  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)\nRequirement already satisfied: plotly>=5.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dash) (5.10.0)\nCollecting Flask>=1.0.4\n  Downloading Flask-2.3.2-py3-none-any.whl (96 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m96.9/96.9 KB\u001b[0m \u001b[31m31.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting dash-html-components==2.0.0\n  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)\nRequirement already satisfied: importlib-metadata>=3.6.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from Flask>=1.0.4->dash) (5.0.0)\nCollecting itsdangerous>=2.1.2\n  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)\nCollecting Werkzeug>=2.3.3\n  Downloading Werkzeug-2.3.3-py3-none-any.whl (242 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m242.3/242.3 KB\u001b[0m \u001b[31m23.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: click>=8.1.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from Flask>=1.0.4->dash) (8.1.3)\nCollecting Jinja2>=3.1.2\n  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m133.1/133.1 KB\u001b[0m \u001b[31m41.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting blinker>=1.6.2\n  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)\nRequirement already satisfied: tenacity>=6.2.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from plotly>=5.0.0->dash) (8.1.0)\nRequirement already satisfied: zipp>=0.5 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->Flask>=1.0.4->dash) (3.9.0)\nRequirement already satisfied: MarkupSafe>=2.0 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from Jinja2>=3.1.2->Flask>=1.0.4->dash) (2.0.0)\nCollecting MarkupSafe>=2.0\n  Downloading MarkupSafe-2.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)\nInstalling collected packages: dash-table, dash-html-components, dash-core-components, MarkupSafe, itsdangerous, blinker, Werkzeug, Jinja2, Flask, dash\n  Attempting uninstall: MarkupSafe\n    Found existing installation: MarkupSafe 2.0.0\n    Not uninstalling markupsafe at /shared-libs/python3.9/py-core/lib/python3.9/site-packages, outside environment /root/venv\n    Can't uninstall 'MarkupSafe'. No files were found to uninstall.\n  Attempting uninstall: Werkzeug\n    Found existing installation: Werkzeug 2.2.2\n    Not uninstalling werkzeug at /shared-libs/python3.9/py/lib/python3.9/site-packages, outside environment /root/venv\n    Can't uninstall 'Werkzeug'. No files were found to uninstall.\n  Attempting uninstall: Jinja2\n    Found existing installation: Jinja2 2.11.3\n    Not uninstalling jinja2 at /shared-libs/python3.9/py-core/lib/python3.9/site-packages, outside environment /root/venv\n    Can't uninstall 'Jinja2'. No files were found to uninstall.\nSuccessfully installed Flask-2.3.2 Jinja2-3.1.2 MarkupSafe-2.1.2 Werkzeug-2.3.3 blinker-1.6.2 dash-2.9.3 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 itsdangerous-2.1.2\n\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\nYou should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: dash-core-components in /root/venv/lib/python3.9/site-packages (2.0.0)\n\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\nYou should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: dash-html-components in /root/venv/lib/python3.9/site-packages (2.0.0)\n\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\nYou should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n\u001b[0mCollecting dash-renderer\n  Downloading dash_renderer-1.9.1.tar.gz (1.0 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.0/1.0 MB\u001b[0m \u001b[31m72.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n\u001b[?25hBuilding wheels for collected packages: dash-renderer\n  Building wheel for dash-renderer (setup.py) ... \u001b[?25ldone\n\u001b[?25h  Created wheel for dash-renderer: filename=dash_renderer-1.9.1-py3-none-any.whl size=1014875 sha256=1a8897344ed51bfb9068c0b06fccfbf3216ef71bceb84c20da21118b32cc5284\n  Stored in directory: /root/.cache/pip/wheels/52/2f/28/956ce9f7763c886d23f0082829bd726e5dacd6c708a5841c77\nSuccessfully built dash-renderer\nInstalling collected packages: dash-renderer\nSuccessfully installed dash-renderer-1.9.1\n\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\nYou should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n\u001b[0mCollecting statsmodels\n  Downloading statsmodels-0.13.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.9/9.9 MB\u001b[0m \u001b[31m138.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: packaging>=21.3 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from statsmodels) (21.3)\nCollecting patsy>=0.5.2\n  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m233.8/233.8 KB\u001b[0m \u001b[31m42.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: numpy>=1.17 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from statsmodels) (1.23.4)\nRequirement already satisfied: scipy>=1.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from statsmodels) (1.9.3)\nRequirement already satisfied: pandas>=0.25 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from statsmodels) (1.2.5)\nRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from packaging>=21.3->statsmodels) (3.0.9)\nRequirement already satisfied: pytz>=2017.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from pandas>=0.25->statsmodels) (2022.5)\nRequirement already satisfied: python-dateutil>=2.7.3 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from pandas>=0.25->statsmodels) (2.8.2)\nRequirement already satisfied: six in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)\nInstalling collected packages: patsy, statsmodels\nSuccessfully installed patsy-0.5.3 statsmodels-0.13.5\n\u001b[33mWARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.\nYou should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}],"execution_count":1},{"cell_type":"code","source":"import dash\nfrom dash import dcc as dcc\nfrom dash import html as html\nimport plotly.graph_objects as go\nimport pandas as pd\nimport numpy as np\nimport plotly.express as px\nfrom sklearn.preprocessing import RobustScaler\nfrom plotly.tools import make_subplots\nfrom statsmodels.tsa.seasonal import seasonal_decompose\nfrom datetime import datetime, timedelta\n\nimport matplotlib.pyplot as plt\nfrom tensorflow.keras.models import Sequential\nfrom tensorflow.keras.layers import Dense, LSTM\nfrom tensorflow.keras.optimizers import Adam\nfrom sklearn.model_selection import GridSearchCV","metadata":{"tags":[],"cell_id":"b65e8021be384dcaa803277ddb8dc76d","source_hash":"2f8967ce","execution_start":1683105000453,"execution_millis":6044,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stderr","text":"2023-05-03 09:10:02.567145: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n2023-05-03 09:10:02.682587: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n2023-05-03 09:10:02.682610: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n2023-05-03 09:10:02.700216: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n2023-05-03 09:10:04.047846: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n2023-05-03 09:10:04.047919: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n2023-05-03 09:10:04.047928: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n","output_type":"stream"}],"execution_count":2},{"cell_type":"code","source":"import seaborn as sns\nimport matplotlib.pyplot as plt\n%matplotlib inline","metadata":{"tags":[],"cell_id":"10706c2f77f646648619a30d2983170a","source_hash":"73e3c08b","execution_start":1683105006436,"execution_millis":131,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":3},{"cell_type":"code","source":"ccpiData = pd.read_csv('ccpi_m.csv')\necpiData = pd.read_csv('ecpi_m.csv')\nfcpiData = pd.read_csv('fcpi_m.csv')\nhcpiData = pd.read_csv('hcpi_m.csv')\nppiData = pd.read_csv('ppi_m.csv')","metadata":{"tags":[],"cell_id":"f6a0a1b4427140fbb0b0970214a372b8","source_hash":"442bd207","execution_start":1683105006568,"execution_millis":678,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":4},{"cell_type":"code","source":"ccpiCountryCodes = ccpiData[['IMF Country Code','Country Code','Country']]\necpiCountryCodes = ecpiData[['IMF Country Code','Country Code','Country']]\nfcpiCountryCodes = fcpiData[['IMF Country Code','Country Code','Country']]\nhcpiCountryCodes = hcpiData[['IMF Country Code','Country Code','Country']]\nppiCountryCodes = ppiData[['IMF Country Code','Country Code','Country']]","metadata":{"tags":[],"cell_id":"d199057c5c894b53a3786036c78c90cb","source_hash":"fff6c6dd","execution_start":1683105006923,"execution_millis":322,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":5},{"cell_type":"code","source":"ccpiCountryCodes.columns = [col + ' CCPI' for col in ccpiCountryCodes.columns]\necpiCountryCodes.columns = [col + ' ECPI' for col in ecpiCountryCodes.columns]\nfcpiCountryCodes.columns = [col + ' FCPI' for col in fcpiCountryCodes.columns]\nhcpiCountryCodes.columns = [col + ' HCPI' for col in hcpiCountryCodes.columns]\nppiCountryCodes.columns = [col + ' PPI' for col in ppiCountryCodes.columns]","metadata":{"tags":[],"cell_id":"b128d1a48ed4458287eac8194b54eaf9","source_hash":"aba09ff","execution_start":1683105006943,"execution_millis":303,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":6},{"cell_type":"code","source":"commonCountryCodes = ccpiCountryCodes.join(\n    ecpiCountryCodes.set_index('IMF Country Code ECPI'), \n    on='IMF Country Code CCPI', how = 'inner').join(\n        fcpiCountryCodes.set_index('IMF Country Code FCPI'), \n        on='IMF Country Code CCPI', how = 'inner').join(\n            hcpiCountryCodes.set_index('IMF Country Code HCPI'),\n             on='IMF Country Code CCPI', how = 'inner'\n             ).join(ppiCountryCodes.set_index('IMF Country Code PPI'), \n             on='IMF Country Code CCPI', how = 'inner').drop_duplicates(\n                 subset='IMF Country Code CCPI')","metadata":{"tags":[],"cell_id":"39b9f80e64874edf9435e9268c82f0bc","source_hash":"6f00ff52","execution_start":1683105006945,"execution_millis":302,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":7},{"cell_type":"code","source":"commonCountryCodesList = commonCountryCodes['Country Code CCPI'].tolist()\ncommonCountryNamesList = commonCountryCodes['Country CCPI'].tolist()","metadata":{"tags":[],"cell_id":"790a8b233d2d49828d63a09605507f42","source_hash":"43139f1b","execution_start":1683105006948,"execution_millis":299,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":8},{"cell_type":"code","source":"def segregate_train_test_data(data, window_size):\n    X, y = [], []\n    for i in range(window_size, len(data)):\n        X.append(data[i-window_size:i])\n        y.append(data[i])\n    return np.array(X), np.array(y)","metadata":{"tags":[],"cell_id":"df9050e8a60649ecb8cef29802ca1a36","source_hash":"e158f255","execution_start":1683105006949,"execution_millis":298,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":9},{"cell_type":"code","source":"result = pd.read_csv('lstmHyperParameters.csv')\nresult.set_index('index', inplace=True)","metadata":{"tags":[],"cell_id":"0f87882cb69d4286888a86f887c8537d","source_hash":"27978d6c","execution_start":1683105006948,"execution_millis":300,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":10},{"cell_type":"code","source":"result_dict = result.to_dict(orient='index')","metadata":{"tags":[],"cell_id":"259f492486af48679d6fa63fdad01933","source_hash":"850f683e","execution_start":1683105006950,"execution_millis":297,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[],"execution_count":11},{"cell_type":"code","source":"if __name__ == '__main__':\n\n    app = dash.Dash()\n\n    def readCountryData(country_code):\n\n        ccpiData = pd.read_csv('ccpi_m.csv')\n        ecpiData = pd.read_csv('ecpi_m.csv')\n        fcpiData = pd.read_csv('fcpi_m.csv')\n        hcpiData = pd.read_csv('hcpi_m.csv')\n        ppiData = pd.read_csv('ppi_m.csv')\n\n        ccpiData = ccpiData[ccpiData['Country Code'] ==country_code].iloc[:,4:-1]\n        ecpiData = ecpiData[ecpiData['Country Code'] ==country_code].iloc[:,4:-1]\n        fcpiData = fcpiData[fcpiData['Country Code'] ==country_code].iloc[:,4:-1]\n        hcpiData = hcpiData[hcpiData['Country Code'] ==country_code].iloc[:,4:-1]\n        ppiData = ppiData[ppiData['Country Code'] ==country_code].iloc[:,4:-1]\n\n        rawDF = pd.concat([ccpiData, ecpiData, fcpiData, hcpiData, ppiData])\n        rawDF = rawDF.T\n        rawDF.rename(columns=rawDF.iloc[0,:], inplace = True)\n        rawDF = rawDF.tail(-1)\n        rawDF.drop(rawDF.tail(1).index,inplace=True)\n        time = pd.DatetimeIndex([i[:-2]+'-'+i[-2:] for i in rawDF.index])\n        rawDF = rawDF.set_index(time)\n        df = rawDF.fillna(method='ffill').fillna(method='bfill')\n\n        dataGreaterthan2003 = df[df.index >= '2003-01-01']\n        return dataGreaterthan2003\n\n    structureDF = readCountryData('ALB')\n    \n    countryCodeDropdown = html.Div([dcc.Dropdown(\n        id='country-selection-dropdown',\n        options=[{'label': i, 'value': j} for i, j in zip(commonCountryNamesList, commonCountryCodesList)],\n        value=commonCountryCodesList[0]\n        )])\n    displayCountryName = html.Div(id='country-selected')\n    displaySelectedMonth = html.Div(id='world-map-month-selected')\n    displayPredictionMonths = html.Div(id='prediction-months-selected')\n    precisionDropdown =  html.Div([\n        dcc.Dropdown(\n            id='precision-selection-dropdown',\n            options=[\n                {'label': 'Low', 'value': 'low'},\n                {'label': 'Medium', 'value': 'medium'},\n                {'label': 'High', 'value': 'high'}\n            ],\n            value='low',\n            style={\n                'width': '25%',\n                'margin': 'auto'\n            }\n        )\n    ], style={\n        'display': 'flex',\n        'justify-content': 'center',\n        'align-items': 'center'\n    })\n\n    @app.callback(dash.dependencies.Output('country-selected', 'children'),\n                dash.dependencies.Input('country-selection-dropdown', 'value'))\n    def update_output(value):\n        country_code = value\n        return html.H3('Country Selected is : ' + commonCountryNamesList[commonCountryCodesList.index(country_code)],\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            )\n\n    @app.callback(dash.dependencies.Output('line-plot', 'figure'),\n                [dash.dependencies.Input('year-range-slider-line-plot', 'value'), \n                 dash.dependencies.Input('country-selection-dropdown', 'value')])\n    def update_line_plot(year_range, value):\n        country_code = value\n        df = readCountryData(country_code)\n\n        df_robust = df.copy()\n        # apply robust scaling\n        for column in df_robust.columns:\n            df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n\n        df = df_robust\n        \n        # filter the DataFrame by the selected year range\n        filtered_df = df[(df.index.year >= year_range[0]) & (df.index.year <= year_range[1])]\n        \n        df = filtered_df\n        \n        # Create a line plot of the dataframe using go.Scatter for each column\n        fig = go.Figure()\n        for col in df.columns:\n            fig.add_trace(go.Scatter(x=df.index, y=df[col], mode='lines', name=col))\n\n        # Set the layout for the plot\n        fig.update_layout(title='Line Plot of inflation indices',\n                        xaxis_title='Year', yaxis_title='Value')\n        \n        return fig    \n\n    @app.callback(dash.dependencies.Output('histogram', 'figure'),\n                [dash.dependencies.Input('year-range-slider-histogram', 'value'), \n                 dash.dependencies.Input('country-selection-dropdown', 'value')])\n    def update_histogram(year_range, value):\n        country_code = value\n        df = readCountryData(country_code)\n\n        df_robust = df.copy()\n        # apply robust scaling\n        for column in df_robust.columns:\n            df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n\n        df = df_robust\n        \n        # filter the DataFrame by the selected year range\n        filtered_df = df[(df.index.year >= year_range[0]) & (df.index.year <= year_range[1])]\n        \n        traces = []\n        for col in filtered_df.columns:\n            trace = go.Histogram(x=filtered_df[col], name=col, opacity=0.3, nbinsx=30)\n            traces.append(trace)\n        \n        layout = go.Layout(title='Histogram plot of inflation indices',barmode='overlay')\n        \n        fig = go.Figure(data=traces, layout=layout)\n        \n        return fig\n   \n    @app.callback(dash.dependencies.Output('inflation-violin-plot', 'figure'),\n                [dash.dependencies.Input('year-range-slider-violin', 'value'), \n                 dash.dependencies.Input('country-selection-dropdown', 'value')])\n    def update_violin_plot(year_range, value):\n        \n        country_code = value\n        df = readCountryData(country_code)\n\n        df_robust = df.copy()\n        # apply robust scaling\n        for column in df_robust.columns:\n            df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n\n        df = df_robust\n    \n        # filter the DataFrame by the selected year range\n        filtered_df = df[(df.index.year >= year_range[0]) & (df.index.year <= year_range[1])]\n        # create a list of violin traces for each column\n        traces = [go.Violin(y=filtered_df[col], name=col) for col in filtered_df.columns]\n        # create the figure object and return it\n        fig = go.Figure(data=traces)\n        fig.update_layout(title='Inflation Indices Violin Plots for Selected Year Range')\n        return fig\n\n    @app.callback(dash.dependencies.Output('pair-plot', 'figure'),\n                [dash.dependencies.Input('year-range-slider-pair-plot', 'value'), \n                 dash.dependencies.Input('country-selection-dropdown', 'value')])\n    def update_pair_plot(year_range, value):\n        country_code = value\n        df = readCountryData(country_code)\n\n        df_robust = df.copy()\n        # apply robust scaling\n        for column in df_robust.columns:\n            df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n\n        df = df_robust\n        \n        # filter the DataFrame by the selected year range\n        filtered_df = df[(df.index.year >= year_range[0]) & (df.index.year <= year_range[1])]\n        \n        df = filtered_df\n        \n        fig = make_subplots(rows=len(df.columns), cols=len(df.columns), shared_xaxes=False, shared_yaxes=False)\n\n        for i in range(len(df.columns)):\n            for j in range(len(df.columns)):\n                scatter_trace = go.Scatter(\n                    x=df.iloc[:, i],\n                    y=df.iloc[:, j],\n                    mode='markers',\n                    showlegend=False\n                )\n                hist_trace = go.Histogram(\n                    x=df.iloc[:, i],\n                    nbinsx=30,\n                    showlegend=False\n                )\n                if i == j:\n                    fig.add_trace(hist_trace, row=i+1, col=j+1)\n                    fig.update_xaxes(title_text=df.columns[i].replace(' Price Index',''), row=i+1, col=j+1, tickfont=dict(size=7))\n                    fig.update_yaxes(title_text=df.columns[j].replace(' Price Index',''), row=i+1, col=j+1, tickfont=dict(size=7))\n                else:\n                    fig.add_trace(scatter_trace, row=i+1, col=j+1)\n                    fig.update_xaxes(title_text=df.columns[i].replace(' Price Index',''), row=i+1, col=j+1, tickfont=dict(size=7))\n                    fig.update_yaxes(title_text=df.columns[j].replace(' Price Index',''), row=i+1, col=j+1, tickfont=dict(size=7))\n\n        fig.update_layout(height=1300, width=1300, title='Pair plot of inflation indices')\n        \n        return fig\n\n    @app.callback(dash.dependencies.Output('time-series-decomposition-plot', 'figure'),\n                [dash.dependencies.Input('time-series-decomposition-radio-buttons', 'value'),\n                 dash.dependencies.Input('year-range-slider-time-series-decomposition', 'value'), \n                 dash.dependencies.Input('country-selection-dropdown', 'value')])\n    def update_time_series_decomposition_plot(selected_index, year_range, value):\n        \n        country_code = value\n        df = readCountryData(country_code)\n\n        df_robust = df.copy()\n        # apply robust scaling\n        for column in df_robust.columns:\n            df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n\n        df = df_robust\n        \n        # filter the DataFrame by the selected year range\n        filtered_df = df[(df.index.year >= year_range[0]) & (df.index.year <= year_range[1])]\n        \n        df = filtered_df\n        \n        time_series_decomposition = seasonal_decompose(x=df[selected_index], model='additive', period=12)\n        trend_decomposition = time_series_decomposition.trend\n        seasonal_decomposition = time_series_decomposition.seasonal\n        residual_decomposition = time_series_decomposition.resid\n        \n        fig = make_subplots(rows=4, \n                            cols=1, \n                            shared_xaxes=False, \n                            shared_yaxes=False, \n                            subplot_titles=(\n                                selected_index, \n                                selected_index  + ' Trend', \n                                selected_index + ' Seasonal', \n                                selected_index + ' Residual'))\n        \n        fig.add_trace(go.Scatter(x=df.index, y=df[selected_index], mode='lines', name=selected_index, showlegend=False), row = 1, col = 1)\n\n        fig.add_trace(go.Scatter(x=df.index, y=trend_decomposition, mode='lines', name=selected_index + ' Trend', showlegend=False), row = 2, col = 1)\n\n        fig.add_trace(go.Scatter(x=df.index, y=seasonal_decomposition, mode='lines', name=selected_index + ' Seasonal', showlegend=False), row = 3, col = 1)\n\n        fig.add_trace(go.Scatter(x=df.index, y=residual_decomposition, mode='lines', name=selected_index + ' Residual', showlegend=False), row = 4, col = 1)\n        \n        fig.update_layout(height=800, width=1300, title='Time Series Decomposition plot of inflation indices')\n        \n        return fig\n    \n    @app.callback(dash.dependencies.Output('world-map-month-selected', 'children'),\n                dash.dependencies.Input('world-map-month-picker', 'date'))\n    def update_selected_month_output(value):\n        date = value\n        month = pd.to_datetime(date).strftime('%B')\n        year = pd.to_datetime(date).year\n        return html.H4('Month selected : ' + str(month) + ' ' + str(year),\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            )\n\n    @app.callback(\n        dash.dependencies.Output('world-map-inflation-index', 'figure'),\n        [dash.dependencies.Input('world-map-month-picker', 'date'),\n         dash.dependencies.Input('world-map-radio-buttons', 'value')]\n    )\n    def update_world_map(date, selected_index):\n        \n        month = str(pd.to_datetime(date).strftime(\"%m\"))\n        year = str(pd.to_datetime(date).year)\n        \n        column_name = str(year) + str(month)\n        \n        if selected_index == 'Official Core Consumer Price Index':\n            ccpiData = pd.read_csv('ccpi_m.csv')\n            ccpiData = ccpiData[['Country Code', 'Country', column_name]]\n            df = ccpiData\n        elif selected_index == 'Energy Price Index':\n            ecpiData = pd.read_csv('ecpi_m.csv')\n            ecpiData = ecpiData[['Country Code', 'Country', column_name]]\n            df = ecpiData\n        elif selected_index == 'Food Price Index':\n            fcpiData = pd.read_csv('fcpi_m.csv')\n            fcpiData = fcpiData[['Country Code', 'Country', column_name]]\n            df = fcpiData\n        elif selected_index == 'Headline Consumer Price Index':\n            hcpiData = pd.read_csv('hcpi_m.csv')\n            hcpiData = hcpiData[['Country Code', 'Country', column_name]]\n            df = hcpiData\n        else:\n            ppiData = pd.read_csv('ppi_m.csv')\n            ppiData = ppiData[['Country Code', 'Country', column_name]]\n            df = ppiData\n            \n        df[column_name] = np.log(df[column_name])\n               \n        fig = px.choropleth(df, locations='Country', \n                            locationmode='country names', \n                            color=column_name,\n                            color_continuous_scale='Viridis',\n                            range_color=[df[column_name].min(), df[column_name].max()],\n                            color_continuous_midpoint=df[column_name].median(),\n                            projection='orthographic')\n        \n        #fig.update_layout(autosize=True)\n        fig.update_layout(height=700, width=1200, autosize=True)\n        \n        return fig\n    \n    @app.callback(\n        dash.dependencies.Output('prediction-months-selected', 'children'),\n        dash.dependencies.Input('prediction-month-picker', 'start_date'),\n        dash.dependencies.Input('prediction-month-picker', 'end_date'),\n        dash.dependencies.Input('precision-selection-dropdown','value')\n    )\n    def update_prediction_months_output(start_date, end_date, precision):\n        \n        start_month = pd.to_datetime(start_date).strftime('%B')\n        start_year = pd.to_datetime(start_date).year\n\n        end_month = pd.to_datetime(end_date).strftime('%B')\n        end_year = pd.to_datetime(end_date).year\n        return html.H4('Start Month : ' + str(start_month) + ' ' + str(start_year) + ', End Month : ' + str(end_month) + ' ' + str(end_year) + ', Precision : ' + precision,\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            )\n    \n    @app.callback(\n        dash.dependencies.Output('inflation-index-prediction', 'figure'),\n        [dash.dependencies.Input('prediction-month-picker', 'start_date'),\n        dash.dependencies.Input('prediction-month-picker', 'end_date'),\n        dash.dependencies.Input('prediction-radio-buttons', 'value'),\n        dash.dependencies.Input('precision-selection-dropdown','value'),\n        dash.dependencies.Input('country-selection-dropdown', 'value')]\n    )\n    def update_prediction_months_output(start_date, end_date, index, precision, country_code):\n\n        df = readCountryData(country_code)\n\n        # select the 'values' column\n        values_col = df[index]\n\n        # calculate the median and quartiles of the column\n        median = values_col.median()\n        q25 = values_col.quantile(0.25)\n        q75 = values_col.quantile(0.75)\n\n        # apply the formula to normalize the values\n        values_col = (values_col - median) / (q75 - q25)\n\n        # update the column in the original dataframe\n        df[index] = values_col\n\n        test_size = 12\n\n        #test sets\n        lstmTestDF = df.tail(12)\n\n        # train sets\n        # get the number of rows in the dataframe\n        num_rows = df.shape[0]\n\n        # get all rows except the last 12 rows\n        lstmTrainDF = df.iloc[:num_rows-12, :]\n\n        X_train_dict = {}\n        y_train_dict = {}\n        X_test_dict = {}\n        y_test_dict = {}\n        window = 3\n\n        col = index\n\n        X_train_dict[col], y_train_dict[col] = segregate_train_test_data(data=lstmTrainDF[col], window_size=window)\n        X_test_dict[col], y_test_dict[col] = segregate_train_test_data(data=lstmTestDF[col], window_size=window)\n        X_train_dict[col] = np.reshape(X_train_dict[col], (X_train_dict[col].shape[0], X_train_dict[col].shape[1], 1))\n        X_test_dict[col] = np.reshape(X_test_dict[col], (X_test_dict[col].shape[0], X_test_dict[col].shape[1], 1))\n            \n        X_dict = {}\n        y_dict = {}\n  \n        X_dict[col], y_dict[col] = segregate_train_test_data(data=lstmTrainDF[col], window_size=3)\n        X_dict[col] = np.reshape(X_dict[col], (X_dict[col].shape[0], X_dict[col].shape[1], 1))   \n        \n        learning_rate = result_dict[col]['learning_rate']\n        epochs = result_dict[col]['epochs']\n\n        def create_lstm_model_implementation(col, learning_rate, epochs):\n            model = Sequential()\n            model.add(LSTM(64, input_shape=(X_train_dict[col].shape[1], X_train_dict[col].shape[2])))\n            model.add(Dense(1))\n            optimizer = Adam(learning_rate=learning_rate)\n            model.compile(loss='mse', optimizer=optimizer)\n            model.fit(X_train_dict[col], y_train_dict[col], epochs=epochs, batch_size=64, validation_data=(X_test_dict[col], y_test_dict[col]))\n            return model\n\n        if (precision == 'low'):\n            model = create_lstm_model_implementation(col= col,learning_rate=learning_rate ,epochs=epochs)\n        elif (precision == 'medium'):\n            model = create_lstm_model_implementation(col= col,learning_rate=learning_rate / 5 ,epochs=epochs * 5)\n        else:\n            model = create_lstm_model_implementation(col= col,learning_rate=learning_rate / 10 ,epochs=epochs * 10)\n\n        predictions = model.predict(X_test_dict[col])\n\n        start_date = pd.to_datetime(start_date)\n        end_date = pd.to_datetime(end_date) \n\n        # make predictions for future values\n        future_dates = pd.date_range(start_date,end_date, freq='MS')\n        future_values = []\n        last_data = df[[col]].tail(3)\n\n        for i in range(len(future_dates)):\n            X = np.expand_dims(last_data, axis=0)\n            y_pred = model.predict(X)[0][0]\n            future_values.append(y_pred)\n            last_data = np.vstack((last_data[1:], [y_pred]))\n\n        future_data = pd.DataFrame(future_values, columns= ['prediction'], index=future_dates)\n\n        actual_trace = go.Scatter(x=df.index, y=df[col], mode='lines', name='Actual')\n        prediction_trace = go.Scatter(x=future_data.index, y=future_data['prediction'], mode='lines', name='Prediction')\n\n        layout = go.Layout(title='Inflation indices prediction',\n                            xaxis=dict(title='Date'),\n                            yaxis=dict(title='Value'))\n\n        fig = go.Figure(data=[actual_trace, prediction_trace], layout=layout)\n\n\n        return fig\n\n    app.layout = html.Div([\n    html.H1(children='Current Topics In Data Science',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    html.Br(),\n    countryCodeDropdown,\n    displayCountryName,\n    html.Hr(),\n    html.H4(children='Select year range to view Line Plot plots for Inflation indices',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    dcc.RangeSlider(\n        id='year-range-slider-line-plot',\n        min=structureDF.index.year.min(),\n        max=structureDF.index.year.max(),\n        step=1,\n        marks={year: str(year) for year in structureDF.index.year.unique()},\n        value=[structureDF.index.year.min(), structureDF.index.year.max()]\n    ),\n    html.Div([\n    dcc.Loading(id=\"loading-icon-line-plot\", children=[\n        dcc.Graph(id='line-plot')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='line-plot'),\n    html.Hr(),\n    html.H4(children='Select year range to view Histogram plots for Inflation indices',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    dcc.RangeSlider(\n        id='year-range-slider-histogram',\n        min=structureDF.index.year.min(),\n        max=structureDF.index.year.max(),\n        step=1,\n        marks={year: str(year) for year in structureDF.index.year.unique()},\n        value=[structureDF.index.year.min(), structureDF.index.year.max()]\n    ),\n    html.Div([\n    dcc.Loading(id=\"loading-icon-histogram\", children=[\n        dcc.Graph(id='histogram')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='histogram'),\n    html.Hr(),\n    html.H4(children='Select year range to view violin plots for Inflation indices',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    dcc.RangeSlider(\n        id='year-range-slider-violin',\n        min=structureDF.index.year.min(),\n        max=structureDF.index.year.max(),\n        step=1,\n        marks={year: str(year) for year in structureDF.index.year.unique()},\n        value=[structureDF.index.year.min(), structureDF.index.year.max()]\n    ),\n    html.Div([\n    dcc.Loading(id=\"loading-icon-inflation-violin-plot\", children=[\n        dcc.Graph(id='inflation-violin-plot')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='inflation-violin-plot'),\n    html.Hr(),\n    html.H4(children='Select year range to view pair plots for Inflation indices',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    dcc.RangeSlider(\n        id='year-range-slider-pair-plot',\n        min=structureDF.index.year.min(),\n        max=structureDF.index.year.max(),\n        step=1,\n        marks={year: str(year) for year in structureDF.index.year.unique()},\n        value=[structureDF.index.year.min(), structureDF.index.year.max()]\n    ),\n    html.Div([\n    dcc.Loading(id=\"loading-icon-pair-plot\", children=[\n        dcc.Graph(id='pair-plot')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='pair-plot'),\n    html.Hr(),\n    html.Div([\n            html.H4('Select index to Display:'),\n            dcc.RadioItems(\n                id='time-series-decomposition-radio-buttons',\n                options=[\n                    {'label': 'Official Core Consumer Price Index', 'value': 'Official Core Consumer Price Index'},\n                    {'label': 'Energy Price Index', 'value': 'Energy Price Index'},\n                    {'label': 'Food Price Index', 'value': 'Food Price Index'},\n                    {'label': 'Headline Consumer Price Index', 'value': 'Headline Consumer Price Index'},\n                    {'label': 'Producer Price Index', 'value': 'Producer Price Index'},\n                ],\n                value='Official Core Consumer Price Index'\n            ),\n        ], style={'textAlign': 'center'}),\n    html.H4(children='Select year range to view time-series decomposition plots for Inflation indices',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    dcc.RangeSlider(\n        id='year-range-slider-time-series-decomposition',\n        min=structureDF.index.year.min(),\n        max=structureDF.index.year.max(),\n        step=1,\n        marks={year: str(year) for year in structureDF.index.year.unique()},\n        value=[structureDF.index.year.min(), structureDF.index.year.max()]\n    ),\n    html.Div([\n    dcc.Loading(id=\"loading-icon-time-series-decomposition-plot\", children=[\n        dcc.Graph(id='time-series-decomposition-plot')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='time-series-decomposition-plot'),\n    html.Hr(),\n    html.H4(children='Select a month to view Inflation indices for available countries',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    html.Div(\n        dcc.DatePickerSingle(\n            id='world-map-month-picker',\n            date=structureDF.index.max(),\n            clearable=True,\n            with_portal=True,\n            min_date_allowed=structureDF.index.min(),\n            max_date_allowed=structureDF.index.max(),\n            display_format='MMM Y'\n        ), style={'textAlign': 'center',\n                    'color': '#000205'}\n    ),\n    html.Div([\n            html.H4('Select index to Display:'),\n            dcc.RadioItems(\n                id='world-map-radio-buttons',\n                options=[\n                    {'label': 'Official Core Consumer Price Index', 'value': 'Official Core Consumer Price Index'},\n                    {'label': 'Energy Price Index', 'value': 'Energy Price Index'},\n                    {'label': 'Food Price Index', 'value': 'Food Price Index'},\n                    {'label': 'Headline Consumer Price Index', 'value': 'Headline Consumer Price Index'},\n                    {'label': 'Producer Price Index', 'value': 'Producer Price Index'},\n                ],\n                value='Official Core Consumer Price Index'\n            ),\n        ], style={'textAlign': 'center'}),\n    displaySelectedMonth,\n    html.Div([\n    dcc.Loading(id=\"loading-icon-world-map-inflation-index\", children=[\n        dcc.Graph(id='world-map-inflation-index')\n    ], type=\"circle\")\n    ]),\n    #dcc.Graph(id='world-map-inflation-index'),\n    html.Hr(),\n    html.H3(children='Inflation predictions',\n            style={'textAlign': 'center',\n                    'color': '#000205'}\n            ),\n    html.Div([\n        html.H4('Select index to Display:'),\n        dcc.RadioItems(\n            id='prediction-radio-buttons',\n            options=[\n                {'label': 'Official Core Consumer Price Index', 'value': 'Official Core Consumer Price Index'},\n                {'label': 'Energy Price Index', 'value': 'Energy Price Index'},\n                {'label': 'Food Price Index', 'value': 'Food Price Index'},\n                {'label': 'Headline Consumer Price Index', 'value': 'Headline Consumer Price Index'},\n                {'label': 'Producer Price Index', 'value': 'Producer Price Index'},\n            ],\n            value='Official Core Consumer Price Index'\n        ),\n    ], style={'textAlign': 'center'}),\n    html.Div([\n        html.H4('Select Start and End months:'),\n        dcc.DatePickerRange(\n            id='prediction-month-picker',\n            start_date_placeholder_text=\"Start Period\",\n            end_date_placeholder_text=\"End Period\",\n            clearable=True,\n            with_portal=True,\n            min_date_allowed=structureDF.index.max(),\n            max_date_allowed=structureDF.index.max()+ timedelta(days=5*365),\n            display_format='MMM Y'\n    )], style={'textAlign': 'center',\n                    'color': '#000205'}\n    ),\n    html.H4(children='Select precision level:',\n                style={'textAlign': 'center'}\n        ),\n    precisionDropdown,\n    displayPredictionMonths,\n    dcc.Loading(\n        id=\"loading-inflation-index-prediction\",\n        children=dcc.Graph(\n            id='inflation-index-prediction',\n            figure={}\n        ),\n        type=\"circle\",\n    ),\n    html.Hr()\n    ])\n    app.run(host='0.0.0.0', port=8080)\n   ","metadata":{"tags":[],"cell_id":"fadfe8e500b7473a99c493146047835e","source_hash":"246df9d3","execution_start":1683105006960,"execution_millis":14130,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Dash is running on http://0.0.0.0:8080/\n\n * Serving Flask app '__main__'\n * Debug mode: off\n\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n * Running on all addresses (0.0.0.0)\n * Running on http://127.0.0.1:8080\n * Running on http://172.3.165.178:8080\n\u001b[33mPress CTRL+C to quit\u001b[0m\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET / HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_9_3m1683104985.12.1.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_9_3m1683104985.min.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_9_2m1683104985.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/deps/react@16.v2_9_3m1683104985.14.0.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_9_3m1683104985.14.0.min.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_9_3m1683104985.8.1.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_11m1683104985.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_2_4m1683104985.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:13] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_9_2m1683104985.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:14] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:14] \"GET /_dash-layout HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:14] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:14] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:14] \"GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:14] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:14] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:14] \"GET /_dash-component-suites/dash/dcc/async-datepicker.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:10:15] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:10:15] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:15] \"POST /_dash-update-component HTTP/1.1\" 200 -\n[2023-05-03 09:10:15,101] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 314, in update_prediction_months_output\n    start_month = pd.to_datetime(start_date).strftime('%B')\nAttributeError: 'NoneType' object has no attribute 'strftime'\n172.3.22.214 - - [03/May/2023 09:10:15] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n172.3.22.214 - - [03/May/2023 09:10:19] \"POST /_dash-update-component HTTP/1.1\" 200 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\nException ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\nException ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n[2023-05-03 09:10:21,219] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 80, in update_line_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n172.3.150.40 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:10:21,219] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 162, in update_pair_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.22.214 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n[2023-05-03 09:10:21,350] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 110, in update_histogram\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.22.214 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n[2023-05-03 09:10:21,355] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 337, in update_prediction_months_output\n    values_col = df[index]\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n172.3.150.40 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:10:21,548] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 139, in update_violin_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.22.214 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:10:21,748] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 211, in update_time_series_decomposition_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.150.40 - - [03/May/2023 09:10:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n/shared-libs/python3.9/py/lib/python3.9/site-packages/plotly/tools.py:460: DeprecationWarning:\n\nplotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead\n\n/shared-libs/python3.9/py/lib/python3.9/site-packages/plotly/tools.py:460: DeprecationWarning:\n\nplotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead\n\n2023-05-03 09:10:23.791038: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n2023-05-03 09:10:23.791092: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)\n2023-05-03 09:10:23.791115: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (p-638889fe-2546-41ac-8d2f-f9d8b29d307c): /proc/driver/nvidia/version does not exist\n2023-05-03 09:10:23.791411: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\nTo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n172.3.22.214 - - [03/May/2023 09:10:23] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:23] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:10:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\nEpoch 1/100\n172.3.22.214 - - [03/May/2023 09:10:26] \"POST /_dash-update-component HTTP/1.1\" 200 -\n4/4 [==============================] - 2s 127ms/step - loss: 0.2335 - val_loss: 1.3298\nEpoch 2/100\n4/4 [==============================] - 0s 17ms/step - loss: 0.2015 - val_loss: 1.1758\nEpoch 3/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.1712 - val_loss: 1.0042\nEpoch 4/100\n4/4 [==============================] - 0s 25ms/step - loss: 0.1434 - val_loss: 0.8545\nEpoch 5/100\n4/4 [==============================] - 0s 9ms/step - loss: 0.1166 - val_loss: 0.7045\nEpoch 6/100\n4/4 [==============================] - 0s 21ms/step - loss: 0.0916 - val_loss: 0.5598\nEpoch 7/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.0699 - val_loss: 0.4199\nEpoch 8/100\n4/4 [==============================] - 0s 26ms/step - loss: 0.0495 - val_loss: 0.3061\nEpoch 9/100\n4/4 [==============================] - 0s 9ms/step - loss: 0.0316 - val_loss: 0.2109\nEpoch 10/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.0180 - val_loss: 0.1308\nEpoch 11/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.0083 - val_loss: 0.0740\nEpoch 12/100\n4/4 [==============================] - 0s 24ms/step - loss: 0.0029 - val_loss: 0.0347\nEpoch 13/100\n4/4 [==============================] - 0s 7ms/step - loss: 8.2609e-04 - val_loss: 0.0126\nEpoch 14/100\n4/4 [==============================] - 0s 20ms/step - loss: 9.7789e-04 - val_loss: 0.0039\nEpoch 15/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.0018 - val_loss: 0.0017\nEpoch 16/100\n4/4 [==============================] - 0s 24ms/step - loss: 0.0021 - val_loss: 0.0021\nEpoch 17/100\n4/4 [==============================] - 0s 9ms/step - loss: 0.0018 - val_loss: 0.0040\nEpoch 18/100\n4/4 [==============================] - 0s 20ms/step - loss: 0.0012 - val_loss: 0.0075\nEpoch 19/100\n4/4 [==============================] - 0s 7ms/step - loss: 7.8667e-04 - val_loss: 0.0110\nEpoch 20/100\n4/4 [==============================] - 0s 23ms/step - loss: 6.1007e-04 - val_loss: 0.0147\nEpoch 21/100\n4/4 [==============================] - 0s 17ms/step - loss: 6.0164e-04 - val_loss: 0.0172\nEpoch 22/100\n4/4 [==============================] - 0s 10ms/step - loss: 6.5391e-04 - val_loss: 0.0180\nEpoch 23/100\n4/4 [==============================] - 0s 7ms/step - loss: 6.7622e-04 - val_loss: 0.0173\nEpoch 24/100\n4/4 [==============================] - 0s 7ms/step - loss: 6.6086e-04 - val_loss: 0.0158\nEpoch 25/100\n4/4 [==============================] - 0s 8ms/step - loss: 6.2528e-04 - val_loss: 0.0140\nEpoch 26/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9714e-04 - val_loss: 0.0121\nEpoch 27/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8848e-04 - val_loss: 0.0107\nEpoch 28/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8920e-04 - val_loss: 0.0102\nEpoch 29/100\n4/4 [==============================] - 0s 24ms/step - loss: 5.8811e-04 - val_loss: 0.0102\nEpoch 30/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.9068e-04 - val_loss: 0.0108\nEpoch 31/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9121e-04 - val_loss: 0.0109\nEpoch 32/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8626e-04 - val_loss: 0.0107\nEpoch 33/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.8519e-04 - val_loss: 0.0108\nEpoch 34/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8685e-04 - val_loss: 0.0112\nEpoch 35/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8642e-04 - val_loss: 0.0116\nEpoch 36/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8593e-04 - val_loss: 0.0113\nEpoch 37/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8510e-04 - val_loss: 0.0109\nEpoch 38/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8399e-04 - val_loss: 0.0108\nEpoch 39/100\n4/4 [==============================] - 0s 20ms/step - loss: 5.8522e-04 - val_loss: 0.0108\nEpoch 40/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8729e-04 - val_loss: 0.0102\nEpoch 41/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8411e-04 - val_loss: 0.0104\nEpoch 42/100\n4/4 [==============================] - 0s 16ms/step - loss: 5.8504e-04 - val_loss: 0.0105\nEpoch 43/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8647e-04 - val_loss: 0.0102\nEpoch 44/100\n4/4 [==============================] - 0s 14ms/step - loss: 5.8489e-04 - val_loss: 0.0105\nEpoch 45/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8274e-04 - val_loss: 0.0111\nEpoch 46/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8898e-04 - val_loss: 0.0111\nEpoch 47/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8599e-04 - val_loss: 0.0102\nEpoch 48/100\n4/4 [==============================] - 0s 19ms/step - loss: 5.8898e-04 - val_loss: 0.0102\nEpoch 49/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8257e-04 - val_loss: 0.0110\nEpoch 50/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8855e-04 - val_loss: 0.0113\nEpoch 51/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.8731e-04 - val_loss: 0.0108\nEpoch 52/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8419e-04 - val_loss: 0.0100\nEpoch 53/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8937e-04 - val_loss: 0.0102\nEpoch 54/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8258e-04 - val_loss: 0.0111\nEpoch 55/100\n4/4 [==============================] - 0s 19ms/step - loss: 5.8684e-04 - val_loss: 0.0114\nEpoch 56/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8426e-04 - val_loss: 0.0109\nEpoch 57/100\n4/4 [==============================] - 0s 20ms/step - loss: 5.8909e-04 - val_loss: 0.0102\nEpoch 58/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9237e-04 - val_loss: 0.0107\nEpoch 59/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8276e-04 - val_loss: 0.0109\nEpoch 60/100\n4/4 [==============================] - 0s 11ms/step - loss: 5.8326e-04 - val_loss: 0.0109\nEpoch 61/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8279e-04 - val_loss: 0.0107\nEpoch 62/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8269e-04 - val_loss: 0.0106\nEpoch 63/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8306e-04 - val_loss: 0.0110\nEpoch 64/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.8386e-04 - val_loss: 0.0105\nEpoch 65/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8280e-04 - val_loss: 0.0101\nEpoch 66/100\n4/4 [==============================] - 0s 14ms/step - loss: 5.8291e-04 - val_loss: 0.0102\nEpoch 67/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8317e-04 - val_loss: 0.0106\nEpoch 68/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.8469e-04 - val_loss: 0.0108\nEpoch 69/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.8065e-04 - val_loss: 0.0102\nEpoch 70/100\n4/4 [==============================] - 0s 16ms/step - loss: 5.8569e-04 - val_loss: 0.0103\nEpoch 71/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8214e-04 - val_loss: 0.0105\nEpoch 72/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8321e-04 - val_loss: 0.0104\nEpoch 73/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8629e-04 - val_loss: 0.0105\nEpoch 74/100\n4/4 [==============================] - 0s 14ms/step - loss: 5.9429e-04 - val_loss: 0.0113\nEpoch 75/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8729e-04 - val_loss: 0.0103\nEpoch 76/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8329e-04 - val_loss: 0.0104\nEpoch 77/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8119e-04 - val_loss: 0.0105\nEpoch 78/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8241e-04 - val_loss: 0.0105\nEpoch 79/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.8503e-04 - val_loss: 0.0100\nEpoch 80/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8436e-04 - val_loss: 0.0104\nEpoch 81/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.8120e-04 - val_loss: 0.0102\nEpoch 82/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8281e-04 - val_loss: 0.0106\nEpoch 83/100\n4/4 [==============================] - 0s 18ms/step - loss: 5.8221e-04 - val_loss: 0.0102\nEpoch 84/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8505e-04 - val_loss: 0.0101\nEpoch 85/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8275e-04 - val_loss: 0.0094\nEpoch 86/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8233e-04 - val_loss: 0.0097\nEpoch 87/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8191e-04 - val_loss: 0.0102\nEpoch 88/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8129e-04 - val_loss: 0.0107\nEpoch 89/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8107e-04 - val_loss: 0.0105\nEpoch 90/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.8241e-04 - val_loss: 0.0104\nEpoch 91/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8411e-04 - val_loss: 0.0106\nEpoch 92/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8270e-04 - val_loss: 0.0101\nEpoch 93/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8060e-04 - val_loss: 0.0094\nEpoch 94/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8911e-04 - val_loss: 0.0099\nEpoch 95/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8217e-04 - val_loss: 0.0101\nEpoch 96/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8020e-04 - val_loss: 0.0102\nEpoch 97/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.8179e-04 - val_loss: 0.0102\nEpoch 98/100\n4/4 [==============================] - 0s 20ms/step - loss: 5.8396e-04 - val_loss: 0.0106\nEpoch 99/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8182e-04 - val_loss: 0.0100\nEpoch 100/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.7969e-04 - val_loss: 0.0099\n1/1 [==============================] - 0s 290ms/step\n[2023-05-03 09:10:31,753] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 406, in update_prediction_months_output\n    future_dates = pd.date_range(start_date,end_date, freq='MS')\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py\", line 1069, in date_range\n    dtarr = DatetimeArray._generate_range(\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py\", line 373, in _generate_range\n    raise ValueError(\nValueError: Of the four parameters: start, end, periods, and freq, exactly three must be specified\n172.3.18.60 - - [03/May/2023 09:10:31] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n[2023-05-03 09:10:33,925] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 317, in update_prediction_months_output\n    end_month = pd.to_datetime(end_date).strftime('%B')\nAttributeError: 'NoneType' object has no attribute 'strftime'\n172.3.150.40 - - [03/May/2023 09:10:33] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\nEpoch 1/100\n4/4 [==============================] - 2s 114ms/step - loss: 0.2799 - val_loss: 1.5336\nEpoch 2/100\n4/4 [==============================] - 0s 9ms/step - loss: 0.2492 - val_loss: 1.3674\nEpoch 3/100\n4/4 [==============================] - 0s 24ms/step - loss: 0.2187 - val_loss: 1.2048\nEpoch 4/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.1894 - val_loss: 1.0465\nEpoch 5/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.1625 - val_loss: 0.8876\nEpoch 6/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.1352 - val_loss: 0.7192\nEpoch 7/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.1090 - val_loss: 0.5627\nEpoch 8/100\n4/4 [==============================] - 0s 24ms/step - loss: 0.0842 - val_loss: 0.4098\nEpoch 9/100\n4/4 [==============================] - 0s 7ms/step - loss: 0.0604 - val_loss: 0.2733\nEpoch 10/100\n1/4 [======>.......................] - ETA: 0s - loss: 0.0494172.3.150.40 - - [03/May/2023 09:10:36] \"POST /_dash-update-component HTTP/1.1\" 200 -\n4/4 [==============================] - 0s 24ms/step - loss: 0.0398 - val_loss: 0.1568\nEpoch 11/100\n4/4 [==============================] - 0s 28ms/step - loss: 0.0234 - val_loss: 0.0737\nEpoch 12/100\n4/4 [==============================] - 0s 27ms/step - loss: 0.0108 - val_loss: 0.0264\nEpoch 13/100\n4/4 [==============================] - 0s 31ms/step - loss: 0.0035 - val_loss: 0.0046\nEpoch 14/100\n4/4 [==============================] - 0s 39ms/step - loss: 0.0011 - val_loss: 1.3550e-04\nEpoch 15/100\n4/4 [==============================] - 0s 25ms/step - loss: 0.0016 - val_loss: 0.0025\nEpoch 16/100\n4/4 [==============================] - 0s 27ms/step - loss: 0.0025 - val_loss: 0.0035\nEpoch 17/100\n4/4 [==============================] - 0s 30ms/step - loss: 0.0026 - val_loss: 0.0016\nEpoch 18/100\n4/4 [==============================] - 0s 33ms/step - loss: 0.0020 - val_loss: 1.0028e-04\nEpoch 19/100\n4/4 [==============================] - 0s 27ms/step - loss: 0.0012 - val_loss: 0.0018\nEpoch 20/100\n4/4 [==============================] - 0s 9ms/step - loss: 7.7452e-04 - val_loss: 0.0060\nEpoch 21/100\n4/4 [==============================] - 0s 10ms/step - loss: 6.3596e-04 - val_loss: 0.0106\nEpoch 22/100\n2/4 [==============>...............] - ETA: 0s - loss: 6.4960e-04Epoch 1/100\n4/4 [==============================] - 0s 27ms/step - loss: 6.7140e-04 - val_loss: 0.0136\nEpoch 23/100\n4/4 [==============================] - 0s 32ms/step - loss: 7.1794e-04 - val_loss: 0.0151\nEpoch 24/100\n4/4 [==============================] - 0s 27ms/step - loss: 7.1556e-04 - val_loss: 0.0153\nEpoch 25/100\n4/4 [==============================] - 0s 27ms/step - loss: 6.7221e-04 - val_loss: 0.0141\nEpoch 26/100\n4/4 [==============================] - 0s 33ms/step - loss: 6.2932e-04 - val_loss: 0.0127\nEpoch 27/100\n4/4 [==============================] - 0s 36ms/step - loss: 6.0745e-04 - val_loss: 0.0113\nEpoch 28/100\n4/4 [==============================] - 0s 24ms/step - loss: 6.0122e-04 - val_loss: 0.0108\nEpoch 29/100\n4/4 [==============================] - 0s 9ms/step - loss: 6.0676e-04 - val_loss: 0.0104\nEpoch 30/100\n4/4 [==============================] - 0s 10ms/step - loss: 6.0903e-04 - val_loss: 0.0109\nEpoch 31/100\n4/4 [==============================] - 0s 28ms/step - loss: 6.0645e-04 - val_loss: 0.0114\nEpoch 32/100\n4/4 [==============================] - 0s 30ms/step - loss: 6.0282e-04 - val_loss: 0.0116\nEpoch 33/100\n4/4 [==============================] - 0s 26ms/step - loss: 6.0120e-04 - val_loss: 0.0120\nEpoch 34/100\n4/4 [==============================] - 0s 9ms/step - loss: 6.0287e-04 - val_loss: 0.0123\nEpoch 35/100\n4/4 [==============================] - 0s 10ms/step - loss: 6.0079e-04 - val_loss: 0.0120\nEpoch 36/100\n4/4 [==============================] - 0s 31ms/step - loss: 6.0257e-04 - val_loss: 0.0118\nEpoch 37/100\n4/4 [==============================] - 0s 39ms/step - loss: 6.0214e-04 - val_loss: 0.0117\nEpoch 38/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9975e-04 - val_loss: 0.0116\nEpoch 39/100\n4/4 [==============================] - 0s 28ms/step - loss: 6.0357e-04 - val_loss: 0.0116\nEpoch 40/100\n4/4 [==============================] - 0s 28ms/step - loss: 6.0249e-04 - val_loss: 0.0113\nEpoch 41/100\n4/4 [==============================] - 0s 31ms/step - loss: 6.0069e-04 - val_loss: 0.0112\nEpoch 42/100\n4/4 [==============================] - 0s 27ms/step - loss: 6.0396e-04 - val_loss: 0.0110\nEpoch 43/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.0026e-04 - val_loss: 0.0114\nEpoch 44/100\n4/4 [==============================] - 0s 12ms/step - loss: 5.9902e-04 - val_loss: 0.0117\nEpoch 45/100\n4/4 [==============================] - 0s 9ms/step - loss: 6.0171e-04 - val_loss: 0.0115\nEpoch 46/100\n4/4 [==============================] - 0s 30ms/step - loss: 6.0124e-04 - val_loss: 0.0112\nEpoch 47/100\n4/4 [==============================] - 0s 29ms/step - loss: 5.9931e-04 - val_loss: 0.0113\nEpoch 48/100\n4/4 [==============================] - 0s 42ms/step - loss: 5.9985e-04 - val_loss: 0.0114\nEpoch 49/100\n4/4 [==============================] - 0s 12ms/step - loss: 6.0027e-04 - val_loss: 0.0112\nEpoch 50/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.0559e-04 - val_loss: 0.0111\nEpoch 51/100\n4/4 [==============================] - 0s 30ms/step - loss: 6.0124e-04 - val_loss: 0.0119\nEpoch 52/100\n4/4 [==============================] - 0s 31ms/step - loss: 6.0654e-04 - val_loss: 0.0115\nEpoch 53/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.0119e-04 - val_loss: 0.0118\nEpoch 54/100\n4/4 [==============================] - 0s 26ms/step - loss: 5.9783e-04 - val_loss: 0.0112\nEpoch 55/100\n4/4 [==============================] - 0s 28ms/step - loss: 6.0010e-04 - val_loss: 0.0109\nEpoch 56/100\n4/4 [==============================] - 0s 7ms/step - loss: 6.0199e-04 - val_loss: 0.0113\nEpoch 57/100\n4/4 [==============================] - 0s 32ms/step - loss: 6.0026e-04 - val_loss: 0.0111\nEpoch 58/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.9889e-04 - val_loss: 0.0113\nEpoch 59/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9858e-04 - val_loss: 0.0115\nEpoch 60/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.9812e-04 - val_loss: 0.0119\nEpoch 61/100\n4/4 [==============================] - 0s 28ms/step - loss: 5.9854e-04 - val_loss: 0.0120\nEpoch 62/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.9906e-04 - val_loss: 0.0118\nEpoch 63/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9896e-04 - val_loss: 0.0118\nEpoch 64/100\n4/4 [==============================] - 0s 35ms/step - loss: 6.0365e-04 - val_loss: 0.0118\nEpoch 65/100\n4/4 [==============================] - 0s 9ms/step - loss: 6.0355e-04 - val_loss: 0.0111\nEpoch 66/100\n4/4 [==============================] - 0s 30ms/step - loss: 6.0030e-04 - val_loss: 0.0117\nEpoch 67/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.0035e-04 - val_loss: 0.0119\nEpoch 68/100\n4/4 [==============================] - 0s 26ms/step - loss: 5.9997e-04 - val_loss: 0.0113\nEpoch 69/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9912e-04 - val_loss: 0.0119\nEpoch 70/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9987e-04 - val_loss: 0.0122\nEpoch 71/100\n4/4 [==============================] - 0s 35ms/step - loss: 5.9819e-04 - val_loss: 0.0117\nEpoch 72/100\n4/4 [==============================] - 0s 25ms/step - loss: 5.9831e-04 - val_loss: 0.0110\nEpoch 73/100\n4/4 [==============================] - 0s 28ms/step - loss: 5.9874e-04 - val_loss: 0.0109\nEpoch 74/100\n4/4 [==============================] - 0s 28ms/step - loss: 5.9975e-04 - val_loss: 0.0110\nEpoch 75/100\n4/4 [==============================] - 5s 309ms/step - loss: 0.2396 - val_loss: 1.3856\n4/4 [==============================] - 0s 7ms/step - loss: 5.9722e-04 - val_loss: 0.0106\nEpoch 76/100\nEpoch 2/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9825e-04 - val_loss: 0.0104\n4/4 [==============================] - 0s 9ms/step - loss: 0.2059 - val_loss: 1.2041\nEpoch 77/100\nEpoch 3/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9958e-04 - val_loss: 0.0109\n4/4 [==============================] - 0s 9ms/step - loss: 0.1758 - val_loss: 1.0243\nEpoch 78/100\nEpoch 4/100\n4/4 [==============================] - 0s 30ms/step - loss: 0.1463 - val_loss: 0.8665\n4/4 [==============================] - 0s 30ms/step - loss: 5.9865e-04 - val_loss: 0.0112\nEpoch 5/100\nEpoch 79/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9710e-04 - val_loss: 0.0110\n4/4 [==============================] - 0s 32ms/step - loss: 0.1198 - val_loss: 0.7242\nEpoch 80/100\nEpoch 6/100\n4/4 [==============================] - 0s 10ms/step - loss: 0.0951 - val_loss: 0.5887\n4/4 [==============================] - 0s 10ms/step - loss: 5.9681e-04 - val_loss: 0.0113\nEpoch 7/100\nEpoch 81/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.0728 - val_loss: 0.4603\nEpoch 8/100\n4/4 [==============================] - 0s 10ms/step - loss: 5.9762e-04 - val_loss: 0.0112\nEpoch 82/100\n4/4 [==============================] - 0s 39ms/step - loss: 0.0518 - val_loss: 0.3397\nEpoch 9/100\n4/4 [==============================] - 0s 17ms/step - loss: 5.9720e-04 - val_loss: 0.0112\nEpoch 83/100\n4/4 [==============================] - 0s 8ms/step - loss: 0.0344 - val_loss: 0.2306\n4/4 [==============================] - 0s 8ms/step - loss: 6.0402e-04 - val_loss: 0.0116\nEpoch 10/100\nEpoch 84/100\n4/4 [==============================] - 0s 36ms/step - loss: 6.0253e-04 - val_loss: 0.0108\n4/4 [==============================] - 0s 36ms/step - loss: 0.0203 - val_loss: 0.1393\nEpoch 85/100\nEpoch 11/100\n4/4 [==============================] - 0s 9ms/step - loss: 0.0097 - val_loss: 0.0728\nEpoch 12/100\n4/4 [==============================] - 0s 28ms/step - loss: 5.9781e-04 - val_loss: 0.0113\nEpoch 86/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.9632e-04 - val_loss: 0.0114\n4/4 [==============================] - 0s 31ms/step - loss: 0.0035 - val_loss: 0.0313\nEpoch 87/100\nEpoch 13/100\n4/4 [==============================] - 0s 32ms/step - loss: 0.0010 - val_loss: 0.0113\n4/4 [==============================] - 0s 33ms/step - loss: 5.9791e-04 - val_loss: 0.0114\nEpoch 14/100\nEpoch 88/100\n4/4 [==============================] - 0s 30ms/step - loss: 8.5204e-04 - val_loss: 0.0040\n4/4 [==============================] - 0s 29ms/step - loss: 5.9659e-04 - val_loss: 0.0111\nEpoch 15/100\nEpoch 89/100\n4/4 [==============================] - 0s 31ms/step - loss: 5.9784e-04 - val_loss: 0.0109\n4/4 [==============================] - 0s 31ms/step - loss: 0.0015 - val_loss: 0.0021\nEpoch 90/100\nEpoch 16/100\n4/4 [==============================] - 0s 30ms/step - loss: 5.9597e-04 - val_loss: 0.0106\nEpoch 91/100\n4/4 [==============================] - 0s 32ms/step - loss: 0.0020 - val_loss: 0.0020\nEpoch 17/100\n4/4 [==============================] - 0s 31ms/step - loss: 5.9956e-04 - val_loss: 0.0105\n4/4 [==============================] - 0s 31ms/step - loss: 0.0018 - val_loss: 0.0032\nEpoch 92/100\nEpoch 18/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9650e-04 - val_loss: 0.0105\n4/4 [==============================] - 0s 31ms/step - loss: 0.0013 - val_loss: 0.0056\nEpoch 19/100\nEpoch 93/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9844e-04 - val_loss: 0.0107\n4/4 [==============================] - 0s 32ms/step - loss: 8.3107e-04 - val_loss: 0.0090\nEpoch 94/100\nEpoch 20/100\n4/4 [==============================] - 0s 31ms/step - loss: 5.9902e-04 - val_loss: 0.0108\n4/4 [==============================] - 0s 32ms/step - loss: 6.3410e-04 - val_loss: 0.0129\nEpoch 95/100\nEpoch 21/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.0202e-04 - val_loss: 0.0161\nEpoch 22/100\n4/4 [==============================] - 0s 36ms/step - loss: 5.9570e-04 - val_loss: 0.0110\nEpoch 96/100\n4/4 [==============================] - 0s 29ms/step - loss: 6.4911e-04 - val_loss: 0.0177\nEpoch 23/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9623e-04 - val_loss: 0.0110\nEpoch 97/100\n4/4 [==============================] - 0s 31ms/step - loss: 6.6561e-04 - val_loss: 0.0171\nEpoch 24/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9521e-04 - val_loss: 0.0107\nEpoch 98/100\n4/4 [==============================] - 0s 32ms/step - loss: 6.5503e-04 - val_loss: 0.0156\nEpoch 25/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9481e-04 - val_loss: 0.0104\nEpoch 99/100\n4/4 [==============================] - 0s 32ms/step - loss: 6.2770e-04 - val_loss: 0.0142\nEpoch 26/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9758e-04 - val_loss: 0.0106\nEpoch 100/100\n4/4 [==============================] - 0s 29ms/step - loss: 5.9990e-04 - val_loss: 0.0132\nEpoch 27/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9694e-04 - val_loss: 0.0109\n4/4 [==============================] - 0s 8ms/step - loss: 5.9607e-04 - val_loss: 0.0118\nEpoch 28/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9435e-04 - val_loss: 0.0113\nEpoch 29/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9350e-04 - val_loss: 0.0109\nEpoch 30/100\n4/4 [==============================] - 0s 28ms/step - loss: 5.9399e-04 - val_loss: 0.0106\nEpoch 31/100\n4/4 [==============================] - 0s 29ms/step - loss: 5.9483e-04 - val_loss: 0.0109\nEpoch 32/100\n4/4 [==============================] - 0s 124ms/step - loss: 5.9258e-04 - val_loss: 0.0115\nEpoch 33/100\n4/4 [==============================] - 0s 11ms/step - loss: 5.9114e-04 - val_loss: 0.0122\nEpoch 34/100\n4/4 [==============================] - 0s 13ms/step - loss: 5.9062e-04 - val_loss: 0.0123\nEpoch 35/100\n4/4 [==============================] - 0s 27ms/step - loss: 5.9550e-04 - val_loss: 0.0121\nEpoch 36/100\n4/4 [==============================] - 0s 32ms/step - loss: 5.9441e-04 - val_loss: 0.0122\nEpoch 37/100\n4/4 [==============================] - 0s 38ms/step - loss: 5.8918e-04 - val_loss: 0.0124\nEpoch 38/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9217e-04 - val_loss: 0.0122\nEpoch 39/100\n1/1 [==============================] - 1s 1s/step\n[2023-05-03 09:10:45,958] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 406, in update_prediction_months_output\n    future_dates = pd.date_range(start_date,end_date, freq='MS')\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py\", line 1069, in date_range\n    dtarr = DatetimeArray._generate_range(\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py\", line 373, in _generate_range\n    raise ValueError(\nValueError: Of the four parameters: start, end, periods, and freq, exactly three must be specified\n172.3.150.40 - - [03/May/2023 09:10:45] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n4/4 [==============================] - 0s 31ms/step - loss: 5.9588e-04 - val_loss: 0.0121\nEpoch 40/100\n4/4 [==============================] - 0s 27ms/step - loss: 5.9203e-04 - val_loss: 0.0114\nEpoch 41/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9600e-04 - val_loss: 0.0111\nEpoch 42/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.9260e-04 - val_loss: 0.0118\nEpoch 43/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9637e-04 - val_loss: 0.0127\nEpoch 44/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9394e-04 - val_loss: 0.0119\nEpoch 45/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8937e-04 - val_loss: 0.0117\nEpoch 46/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9134e-04 - val_loss: 0.0116\nEpoch 47/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.9169e-04 - val_loss: 0.0119\nEpoch 48/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9602e-04 - val_loss: 0.0126\nEpoch 49/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.9284e-04 - val_loss: 0.0123\nEpoch 50/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9023e-04 - val_loss: 0.0121\nEpoch 51/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.9266e-04 - val_loss: 0.0119\nEpoch 52/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9243e-04 - val_loss: 0.0125\nEpoch 53/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.9318e-04 - val_loss: 0.0122\nEpoch 54/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9298e-04 - val_loss: 0.0118\nEpoch 55/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9070e-04 - val_loss: 0.0117\nEpoch 56/100\n4/4 [==============================] - 0s 15ms/step - loss: 5.8957e-04 - val_loss: 0.0123\nEpoch 57/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9142e-04 - val_loss: 0.0123\nEpoch 58/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8925e-04 - val_loss: 0.0125\nEpoch 59/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9145e-04 - val_loss: 0.0124\nEpoch 60/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8979e-04 - val_loss: 0.0126\nEpoch 61/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9032e-04 - val_loss: 0.0126\nEpoch 62/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.9905e-04 - val_loss: 0.0127\nEpoch 63/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8492e-04 - val_loss: 0.0113\nEpoch 64/100\n4/4 [==============================] - 0s 23ms/step - loss: 5.9776e-04 - val_loss: 0.0106\nEpoch 65/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.9416e-04 - val_loss: 0.0118\nEpoch 66/100\n4/4 [==============================] - 0s 20ms/step - loss: 5.9493e-04 - val_loss: 0.0121\nEpoch 67/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9214e-04 - val_loss: 0.0115\nEpoch 68/100\n4/4 [==============================] - 0s 19ms/step - loss: 5.9178e-04 - val_loss: 0.0114\nEpoch 69/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9321e-04 - val_loss: 0.0123\nEpoch 70/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9124e-04 - val_loss: 0.0119\nEpoch 71/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8931e-04 - val_loss: 0.0117\nEpoch 72/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9208e-04 - val_loss: 0.0120\nEpoch 73/100\n4/4 [==============================] - 0s 19ms/step - loss: 5.8863e-04 - val_loss: 0.0113\nEpoch 74/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9587e-04 - val_loss: 0.0105\nEpoch 75/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.9431e-04 - val_loss: 0.0117\nEpoch 76/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8753e-04 - val_loss: 0.0125\nEpoch 77/100\n4/4 [==============================] - 0s 20ms/step - loss: 5.9576e-04 - val_loss: 0.0122\nEpoch 78/100\n4/4 [==============================] - 0s 15ms/step - loss: 5.8730e-04 - val_loss: 0.0114\nEpoch 79/100\n4/4 [==============================] - 0s 13ms/step - loss: 5.9000e-04 - val_loss: 0.0110\nEpoch 80/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9094e-04 - val_loss: 0.0112\nEpoch 81/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8764e-04 - val_loss: 0.0111\nEpoch 82/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.8917e-04 - val_loss: 0.0110\nEpoch 83/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8743e-04 - val_loss: 0.0108\nEpoch 84/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.8702e-04 - val_loss: 0.0108\nEpoch 85/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.9095e-04 - val_loss: 0.0112\nEpoch 86/100\n4/4 [==============================] - 0s 11ms/step - loss: 5.8827e-04 - val_loss: 0.0117\nEpoch 87/100\n4/4 [==============================] - 0s 9ms/step - loss: 5.8713e-04 - val_loss: 0.0114\nEpoch 88/100\n4/4 [==============================] - 0s 13ms/step - loss: 5.8628e-04 - val_loss: 0.0113\nEpoch 89/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.9087e-04 - val_loss: 0.0111\nEpoch 90/100\n4/4 [==============================] - 0s 17ms/step - loss: 5.9076e-04 - val_loss: 0.0112\nEpoch 91/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8657e-04 - val_loss: 0.0121\nEpoch 92/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8692e-04 - val_loss: 0.0123\nEpoch 93/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8840e-04 - val_loss: 0.0119\nEpoch 94/100\n4/4 [==============================] - 0s 22ms/step - loss: 5.8677e-04 - val_loss: 0.0116\nEpoch 95/100\n4/4 [==============================] - 0s 8ms/step - loss: 5.8696e-04 - val_loss: 0.0113\nEpoch 96/100\n4/4 [==============================] - 0s 21ms/step - loss: 5.8738e-04 - val_loss: 0.0110\nEpoch 97/100\n4/4 [==============================] - 0s 7ms/step - loss: 5.8731e-04 - val_loss: 0.0119\nEpoch 98/100\n4/4 [==============================] - 0s 19ms/step - loss: 5.8699e-04 - val_loss: 0.0125\nEpoch 99/100\n4/4 [==============================] - 0s 17ms/step - loss: 5.8895e-04 - val_loss: 0.0120\nEpoch 100/100\n4/4 [==============================] - 0s 13ms/step - loss: 5.8822e-04 - val_loss: 0.0115\n1/1 [==============================] - 0s 253ms/step\n1/1 [==============================] - 0s 19ms/step\n1/1 [==============================] - 0s 19ms/step\n1/1 [==============================] - 0s 16ms/step\n1/1 [==============================] - 0s 13ms/step\n1/1 [==============================] - 0s 23ms/step\n1/1 [==============================] - 0s 12ms/step\n172.3.18.60 - - [03/May/2023 09:10:49] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:07] \"GET / HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_9_3m1683104985.12.1.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/deps/react@16.v2_9_3m1683104985.14.0.min.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_9_3m1683104985.14.0.min.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_9_3m1683104985.8.1.min.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_9_3m1683104985.min.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_9_2m1683104985.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_9_2m1683104985.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_11m1683104985.min.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:08] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_2_4m1683104985.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:10] \"GET /_dash-layout HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:10] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:11:11] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:11] \"GET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:11] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:11] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:11:11] \"GET /_dash-component-suites/dash/dcc/async-datepicker.js HTTP/1.1\" 200 -\n172.3.22.214 - - [03/May/2023 09:11:11] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:11:11] \"POST /_dash-update-component HTTP/1.1\" 200 -\n[2023-05-03 09:11:11,787] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 314, in update_prediction_months_output\n    start_month = pd.to_datetime(start_date).strftime('%B')\nAttributeError: 'NoneType' object has no attribute 'strftime'\n172.3.150.40 - - [03/May/2023 09:11:11] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n172.3.22.214 - - [03/May/2023 09:11:12] \"POST /_dash-update-component HTTP/1.1\" 200 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:11:14,083] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 211, in update_time_series_decomposition_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.18.60 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n[2023-05-03 09:11:14,273] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 139, in update_violin_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n172.3.22.214 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n[2023-05-03 09:11:14,278] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 80, in update_line_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.18.60 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n[2023-05-03 09:11:14,282] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 337, in update_prediction_months_output\n    values_col = df[index]\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.150.40 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:11:14,374] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 110, in update_histogram\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.150.40 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:11:14,398] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 162, in update_pair_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.22.214 - - [03/May/2023 09:11:14] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n172.3.22.214 - - [03/May/2023 09:11:23] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:14:04] \"GET / HTTP/1.1\" 200 -\n172.3.150.40 - - [03/May/2023 09:14:05] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:14:05] \"GET /_dash-layout HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:14:05] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\u001b[0m\" 304 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-slider.js HTTP/1.1\u001b[0m\" 304 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\u001b[0m\" 304 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\u001b[0m\" 304 -\n172.3.150.40 - - [03/May/2023 09:14:06] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-datepicker.js HTTP/1.1\u001b[0m\" 304 -\n172.3.150.40 - - [03/May/2023 09:14:06] \"POST /_dash-update-component HTTP/1.1\" 200 -\n[2023-05-03 09:14:06,450] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 314, in update_prediction_months_output\n    start_month = pd.to_datetime(start_date).strftime('%B')\nAttributeError: 'NoneType' object has no attribute 'strftime'\n172.3.18.60 - - [03/May/2023 09:14:06] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n172.3.22.214 - - [03/May/2023 09:14:06] \"POST /_dash-update-component HTTP/1.1\" 200 -\n172.3.18.60 - - [03/May/2023 09:14:06] \"POST /_dash-update-component HTTP/1.1\" 200 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n[2023-05-03 09:14:08,692] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 139, in update_violin_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.150.40 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:14:08,698] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 110, in update_histogram\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.18.60 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:14:08,780] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 337, in update_prediction_months_output\n    values_col = df[index]\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.150.40 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n[2023-05-03 09:14:08,878] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 80, in update_line_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n172.3.22.214 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"},{"output_type":"error","ename":"TypeError","evalue":"'Series' objects are mutable, thus they cannot be hashed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:4588\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.map_locations\u001b[0;34m()\u001b[0m\n","File \u001b[0;32m/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py:1785\u001b[0m, in \u001b[0;36mNDFrame.__hash__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1784\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__hash__\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m-> 1785\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[1;32m   1786\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mrepr\u001b[39m(\u001b[38;5;28mtype\u001b[39m(\u001b[38;5;28mself\u001b[39m)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m objects are mutable, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1787\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mthus they cannot be hashed\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1788\u001b[0m     )\n","\u001b[0;31mTypeError\u001b[0m: 'Series' objects are mutable, thus they cannot be hashed"]},{"name":"stderr","text":"Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'\nTraceback (most recent call last):\n  File \"pandas/_libs/hashtable_class_helper.pxi\", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations\n[2023-05-03 09:14:08,886] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 162, in update_pair_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.22.214 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1785, in __hash__\n    raise TypeError(\nTypeError: 'Series' objects are mutable, thus they cannot be hashed\n[2023-05-03 09:14:08,891] ERROR in app: Exception on /_dash-update-component [POST]\nTraceback (most recent call last):\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 2190, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/root/venv/lib/python3.9/site-packages/flask/app.py\", line 1469, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/root/venv/lib/python3.9/site-packages/dash/dash.py\", line 1283, in dispatch\n    ctx.run(\n  File \"/root/venv/lib/python3.9/site-packages/dash/_callback.py\", line 450, in add_context\n    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n  File \"/tmp/ipykernel_127/1041133795.py\", line 211, in update_time_series_decomposition_plot\n    df_robust[column] = (df_robust[column] - df_robust[column].median())  / (df_robust[column].quantile(0.75) - df_robust[column].quantile(0.25))\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py\", line 3024, in __getitem__\n    indexer = self.columns.get_loc(key)\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3081, in get_loc\n    return self._engine.get_loc(casted_key)\n  File \"pandas/_libs/index.pyx\", line 70, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 96, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas/_libs/index.pyx\", line 109, in pandas._libs.index.IndexEngine._get_loc_duplicates\n  File \"pandas/_libs/index.pyx\", line 176, in pandas._libs.index.IndexEngine.is_monotonic_increasing.__get__\n  File \"pandas/_libs/index.pyx\", line 193, in pandas._libs.index.IndexEngine._do_monotonic_check\n  File \"pandas/_libs/index.pyx\", line 210, in pandas._libs.index.IndexEngine._call_monotonic\n  File \"pandas/_libs/algos.pyx\", line 760, in pandas._libs.algos.is_monotonic\n  File \"/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/generic.py\", line 1442, in __nonzero__\n    raise ValueError(\nValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n172.3.18.60 - - [03/May/2023 09:14:08] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n","output_type":"stream"}],"execution_count":12},{"cell_type":"markdown","source":"<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=638889fe-2546-41ac-8d2f-f9d8b29d307c' target=\"_blank\">\n<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iODBweCIgaGVpZ2h0PSI4MHB4IiB2aWV3Qm94PSIwIDAgODAgODAiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDU0LjEgKDc2NDkwKSAtIGh0dHBzOi8vc2tldGNoYXBwLmNvbSAtLT4KICAgIDx0aXRsZT5Hcm91cCAzPC90aXRsZT4KICAgIDxkZXNjPkNyZWF0ZWQgd2l0aCBTa2V0Y2guPC9kZXNjPgogICAgPGcgaWQ9IkxhbmRpbmciIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgICAgIDxnIGlkPSJBcnRib2FyZCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTEyMzUuMDAwMDAwLCAtNzkuMDAwMDAwKSI+CiAgICAgICAgICAgIDxnIGlkPSJHcm91cC0zIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMjM1LjAwMDAwMCwgNzkuMDAwMDAwKSI+CiAgICAgICAgICAgICAgICA8cG9seWdvbiBpZD0iUGF0aC0yMCIgZmlsbD0iIzAyNjVCNCIgcG9pbnRzPSIyLjM3NjIzNzYyIDgwIDM4LjA0NzY2NjcgODAgNTcuODIxNzgyMiA3My44MDU3NTkyIDU3LjgyMTc4MjIgMzIuNzU5MjczOSAzOS4xNDAyMjc4IDMxLjY4MzE2ODMiPjwvcG9seWdvbj4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0zNS4wMDc3MTgsODAgQzQyLjkwNjIwMDcsNzYuNDU0OTM1OCA0Ny41NjQ5MTY3LDcxLjU0MjI2NzEgNDguOTgzODY2LDY1LjI2MTk5MzkgQzUxLjExMjI4OTksNTUuODQxNTg0MiA0MS42NzcxNzk1LDQ5LjIxMjIyODQgMjUuNjIzOTg0Niw0OS4yMTIyMjg0IEMyNS40ODQ5Mjg5LDQ5LjEyNjg0NDggMjkuODI2MTI5Niw0My4yODM4MjQ4IDM4LjY0NzU4NjksMzEuNjgzMTY4MyBMNzIuODcxMjg3MSwzMi41NTQ0MjUgTDY1LjI4MDk3Myw2Ny42NzYzNDIxIEw1MS4xMTIyODk5LDc3LjM3NjE0NCBMMzUuMDA3NzE4LDgwIFoiIGlkPSJQYXRoLTIyIiBmaWxsPSIjMDAyODY4Ij48L3BhdGg+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMCwzNy43MzA0NDA1IEwyNy4xMTQ1MzcsMC4yNTcxMTE0MzYgQzYyLjM3MTUxMjMsLTEuOTkwNzE3MDEgODAsMTAuNTAwMzkyNyA4MCwzNy43MzA0NDA1IEM4MCw2NC45NjA0ODgyIDY0Ljc3NjUwMzgsNzkuMDUwMzQxNCAzNC4zMjk1MTEzLDgwIEM0Ny4wNTUzNDg5LDc3LjU2NzA4MDggNTMuNDE4MjY3Nyw3MC4zMTM2MTAzIDUzLjQxODI2NzcsNTguMjM5NTg4NSBDNTMuNDE4MjY3Nyw0MC4xMjg1NTU3IDM2LjMwMzk1NDQsMzcuNzMwNDQwNSAyNS4yMjc0MTcsMzcuNzMwNDQwNSBDMTcuODQzMDU4NiwzNy43MzA0NDA1IDkuNDMzOTE5NjYsMzcuNzMwNDQwNSAwLDM3LjczMDQ0MDUgWiIgaWQ9IlBhdGgtMTkiIGZpbGw9IiMzNzkzRUYiPjwvcGF0aD4KICAgICAgICAgICAgPC9nPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+' > </img>\nCreated in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>","metadata":{"created_in_deepnote_cell":true,"deepnote_cell_type":"markdown"}}],"nbformat":4,"nbformat_minor":0,"metadata":{"deepnote":{},"orig_nbformat":2,"deepnote_app_layout":"dashboard","deepnote_notebook_id":"b5d2efff60f3420090c88848bf5cea4e","deepnote_persisted_session":{"createdAt":"2023-03-21T00:15:07.672Z"},"deepnote_execution_queue":[]}}